import PDFDocument from 'pdfkit';

export function generateTimetablePDF(timetable, type, res) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  
  // Pipe directly to response
  doc.pipe(res);

  // Header
  doc.fontSize(20).text(`${type} Exam Timetable`, { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).text('Generated by VOWELS - AI Exam Timetable Conflict Resolver', { align: 'center' });
  doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(2);

  // Table headers
  const tableTop = 150;
  const colWidths = [70, 60, 70, 50, 60, 70, 50];
  const headers = ['Subject', 'Date', 'Time', 'Room', 'Dept', 'Invigilator', 'Students'];
  
  doc.fontSize(10).fillColor('#2563EB');
  let xPos = 50;
  headers.forEach((header, i) => {
    doc.text(header, xPos, tableTop, { width: colWidths[i], align: 'left' });
    xPos += colWidths[i];
  });

  // Draw header line
  doc.moveTo(50, tableTop + 15).lineTo(520, tableTop + 15).stroke();

  // Table rows
  let yPos = tableTop + 25;
  doc.fillColor('#000000').fontSize(8);

  timetable.forEach((exam, index) => {
    if (yPos > 700) {
      doc.addPage();
      yPos = 50;
    }

    xPos = 50;
    const rowData = [
      (exam.subject_name || '').substring(0, 15),
      exam.date || '',
      `${exam.start_time || ''}-${exam.end_time || ''}`,
      exam.room_no || '',
      exam.department || '',
      (exam.faculty_id || '').substring(0, 15),
      `${exam.total_students || ''}/${exam.room_capacity || ''}`
    ];

    rowData.forEach((data, i) => {
      doc.text(data, xPos, yPos, { width: colWidths[i], align: 'left', lineBreak: false });
      xPos += colWidths[i];
    });

    yPos += 18;
  });

  // Footer
  doc.fontSize(8).text(
    `Generated on ${new Date().toLocaleString()}`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  doc.end();
}
